language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

branches:
  only:
    - api

install:
  - python -m pip install -U pip
  - pip install -r requirements.
  - pip install pytest pytest-cov
  - pip install coveralls

script: 
  - pytest --cov=api api/tests/

after_success:
  - coveralls