language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

branches:
  only:
    - api

before_script:
  - pip install -r test_requirements.txt --use-mirrors
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf 3e82fd5159b84bebe9bc6c9fd3959f322e6f7098
  - py.test example/tests.py --cov=example
  - cd -
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy
# command to install dependencies
install:
  - pip install -e . --use-mirrors
  - pip install -U pip
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
  - pip install coverage

# command to run tests
virtualenv:
  system_site_packages: true
  
script:
  - py.test test_run.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  - coverage run test_run.py

after_success:
  - coverage report
  - coveralls