language: python
python:
  - "2.7"
  - "3.4"
    
branches:
  only:
    - api

# command to install dependencies
install:
  - pip install -U pip
  - pip install pytest
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - pytest
  - bundle exec rspec

after_success:
  - coveralls
