os: linux
language: python
python:
  - "3.4.3"

matrix:
  include:
    - os: linux
      language: generic
      env: PYTHON=3.4.3

branches:
  only:
    - api

install:
  - pip install -r requirements.txt
  - python -m pip install -U pip

script: 
  - pytest
  - coverage

after_success:
  - coveralls