language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

branches:
  only:
    - api

# command to install dependencies
install:
  - pip install -U pip
  - pip install pytest
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage

script:
  - py.test
  - coverage run test_run.py

after_success:
  - coverage report
  - coveralls