language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r requirements.txt --use-mirrors
  - py.test test_run.py --cov=/

script:
  - py.test test_run.py --pep8 / -v --cov / --cov-report term-missing
after_success:
  - coveralls