language: python
python:
 - "2.7"
 - "3.4"
before_install:
  - pip install pytest pytest-cov 
  - pip install python-coveralls  # Add me to install python-coveralls
  - pip install coveralls
  - pip install coverage       # Add me to install coverage.py
  - pip install nose           # Add me to install nose

# command to install dependencies
install:
 - pip install -r requirements.txt
# command to run tests
script:
 - pytest
 - nosetests --with-coverage
after_success:
 - coveralls